### ISSUE TITLE
Output formats and input paramaters

### ISSUE THREAD

**Issue by RYucel** [Vaibhavs10/insanely-fast-whisper#1]
How can I define output format such as "srt" or "text" and Can I define VAD filter or spoken language as parameter? Nice work btw. Thank you

**Comment by Vaibhavs10** [comment]
At the moment, you have the option to get the timestamps as well as the raw text blob transcription, for anything else, you'd need to add that yourself.
We're more than open for the community to add this though.

You can pass the language as a parameter (`lang`).

**Comment by Vaibhavs10** [comment]
I'm closing this for now, feel free to re-open if you have any further questions! 🤗

**Comment by RYucel** [comment]
Thanks. How to add language parameter to model? I could not find any argument to add? i.e French, Spanish
