### ISSUE TITLE
How do I use diarisation? --hf_token isn't a recognized command anymore?

### ISSUE THREAD

**Issue by mikus234** [Vaibhavs10/insanely-fast-whisper#100]
How do I use diarisation? --hf_token isn't a recognized command anymore? Thanks in advance.

**Comment by Vaibhavs10** [comment]
Hey @mikus234 - you need to be on the latest version of the `insanely-fast-whisper` to use it!

`pipx install insanely-fast-whisper==0.0.10`

**Comment by mikus234** [comment]
I just installed it today for the first time. I tried running your command tho:

PS C:\Windows\system32> pipx install insanely-fast-whisper==0.0.10 --force
Installing to existing venv 'insanely-fast-whisper'
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\12039\.local\pipx\logs\cmd_2023-12-01_18.26.49_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python <=3.11,>=3.8; 0.0.9 Requires-Python <=3.11,>=3.8
    ERROR: Could not find a version that satisfies the requirement insanely-fast-whisper==0.0.10 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5b0, 0.0.5b1, 0.0.5b2, 0.0.5b3, 0.0.5, 0.0.6, 0.0.7, 0.0.8)
    ERROR: No matching distribution found for insanely-fast-whisper==0.0.10

**Comment by Vaibhavs10** [comment]
Weird. Can you try and run `pipx uninstall insanely-fast-whisper` and then follow that up with `pipx install insanely-fast-whisper --python python3.11`?

**Comment by mikus234** [comment]
FileNotFoundError: [WinError 2] The system cannot find the file specified

python --version gives 3.11.3

so I guess I need to roll back to 3.11?

**Comment by Vaibhavs10** [comment]
I'm not sure what's wrong here tbh and honestly don't have much experience with Windows.

I suggest rolling back to 3.10 and then testing it?

Cc: @patrick91 - have you encountered something like this?

**Comment by mikus234** [comment]
I'll live with it for now, thanks for the help

**Comment by souvikqb** [comment]
@mikus234 This API provides Diarization output with Whisper-v3 - https://developer.monsterapi.ai/reference/post_generate-speech2text-v2

**Comment by llj0824** [comment]
I'm getting the same issue right now:

** Current python version = 3.11.5 **
```
(base) leojiang@bogon interview_to_deepdiveArticle % python --version
Python 3.11.5
```

** Downloading latest version insanely-fast-whisper version **
** insanely-fast-whisper versions > 0.0.8 are being filter because python version requirement **
````
(base) leojiang@bogon interview_to_deepdiveArticle % pipx install insanely-fast-whisper==0.0.13 --force
Fatal error from pip prevented installation. Full pip output in file:

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python <=3.11,>=3.8; 0.0.11 Requires-Python <=3.11,>=3.8; 0.0.12 Requires-Python <=3.11,>=3.8; 0.0.13 Requires-Python <=3.11,>=3.8; 0.0.9 Requires-Python <=3.11,>=3.8
    ERROR: Could not find a version that satisfies the requirement insanely-fast-whisper==0.0.13 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5b0, 0.0.5b1, 0.0.5b2, 0.0.5b3, 0.0.5, 0.0.6, 0.0.7, 0.0.8)
    ERROR: No matching distribution found for insanely-fast-whisper==0.0.13

Error installing insanely-fast-whisper from spec 'insanely-fast-whisper==0.0.13'.
```
