### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by python481516** [Vaibhavs10/insanely-fast-whisper#107]
I am using MacBook Air and I am getting this error:

`AssertionError: Torch not compiled with CUDA enabled`

I thought this should not be applicable to Mac's because they don't have Nvidia GPUs and CUDA can never be enabled? I saw a fix for this in FAQ but I don't think it works on macOS. Any suggestions what I could try?

**Comment by Vaibhavs10** [comment]
Ah it looks like you are not specifying the backend - please set `--device mps` & --`batch-size 2` 

Do look at the CLI options: https://github.com/Vaibhavs10/insanely-fast-whisper#cli-options

**Comment by Vaibhavs10** [comment]
Aha! You're correct and makes sense. Can I request you to open a PR with a fix, please?

(It's okay to say no if you're busy and won't have the time other wise 🤗)

**Comment by python481516** [comment]
Created PR

**Comment by Vaibhavs10** [comment]
Thank you for the PR! I merged it!

(Closing this issue now)
