### ISSUE TITLE
Troubles with optimum

### ISSUE THREAD

**Issue by VirtualRoyalty** [Vaibhavs10/insanely-fast-whisper#114]
Run `pipx install insanely-fast-whisper`

Output:
```
pip seemed to fail to build package:
    optimum

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    FileNotFoundError: [Errno 2] No such file or directory: 'optimum/version.py'
    AssertionError: Error: Could not open 'optimum/version.py' due [Errno 2] No such file or directory: 'optimum/version.py'

Error installing insanely-fast-whisper.
```

Python 3.10.1
macОs Monterey 12.6 , M1

**Comment by Vaibhavs10** [comment]
Hi! @VirtualRoyalty - Can you re-install with a Python version specified. Here's what you'd need to do:
1. `pipx uninstall insanely-fast-whisper` (if it is already installed)
2. `pipx install insanely-fast-whisper --python3.11` (As mentioned here: https://github.com/Vaibhavs10/insanely-fast-whisper#-blazingly-fast-transcriptions-via-your-terminal-%EF%B8%8F)

This should alleviate your issue.

**Comment by jambudipa** [comment]
I have the same problem. Running:
> pipx install insanely-fast-whisper --python3.11
yields:
> pipx: error: unrecognized arguments: --python3.11

**Comment by AlbertoLanaro** [comment]
The correct command to use is:
```sh
$ pipx install insanely-fast-whisper --python python3.11
```

**Comment by jambudipa** [comment]
Yeah I discovered that soon after, thanks.Sent from my iPhoneOn 12 Dec 2023, at 08:46, Alberto Lanaro ***@***.***> wrote:﻿
The correct command to use is:
$ pipx install insanely-fast-whisper --python python3.11

**Comment by hay** [comment]
The command provided by @AlbertoLanaro worked for me.
