### ISSUE TITLE
Mac, install flash-attn, CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by ekavun** [Vaibhavs10/insanely-fast-whisper#118]
Apple Silicon, Ventura 13.6, Python 3.11.

When running:
$ pipx runpip insanely-fast-whisper install flash-attn --no-build-isolation

The first issue was that Wheel was not present. A pipx inject took care of it.
However, the install continues to fail, and I'm not familiar enough with the environment and dependencies to debug further.

--
Output:
$ pipx runpip insanely-fast-whisper install flash-attn --no-build-isolation
Collecting flash-attn
  Using cached flash_attn-2.3.6.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /private/var/folders/s_/5_d2tghj317fp8c877jl2t7m0000gn/T/pip-install-50gdc2wk/flash-attn_4037490f9d924d64b13a867ce66b517a/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/s_/5_dgtgpj3f7fp8c877jl2t7m0000gn/T/pip-install-50gdc2wk/flash-attn_4037490f9d924d64b13a867ce66b517a/setup.py", line 133, in <module>
          CUDAExtension(
        File "/Users/x/Library/Application Support/pipx/venvs/insanely-fast-whisper/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/x/Library/Application Support/pipx/venvs/insanely-fast-whisper/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1203, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/x/Library/Application Support/pipx/venvs/insanely-fast-whisper/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.1.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
'/Users/x/Library/Application Support/pipx/venvs/insanely-fast-whisper/bin/python -m pip install flash-attn --no-build-isolation' failed

--
I saw this reference to MPS "--device-id mps", not sure if it should be used in this context? 
Any hints appreciated!

**Comment by Vaibhavs10** [comment]
Hi @ekavun - Mac devices do not support flash-attn, please use it by setting `--device-id mps` and do not use the `--flash True` flag.

**Comment by SeeknnDestroy** [comment]
@Vaibhavs10 getting the same error when I am trying to install flash-attn to a docker image. Am I missing something?

**Comment by ekavun** [comment]
Thanks for this!
