### ISSUE TITLE
[Question]Process a 2second wav to text cost around 1 minute

### ISSUE THREAD

**Issue by mikeyang01** [Vaibhavs10/insanely-fast-whisper#120]
`
insanely-fast-whisper --file-name .\tmp\1701954781.1698363.wav
`
It cost around 1 mintue to show the following message
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:02
Voila! Your file has been transcribed go check it out over here! output.json
```
Any ideas on this?
OS: Windows
insanely-fast-whisper Version: 0.0.8
python -V Python 3.11.7

**Comment by james-curtis** [comment]
Fifty minutes of voice to text conversion from acc takes two hours, compared to fast Whisper which only takes five minutes

```shell
❯ ffmpeg -i out.aac 
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[aac @ 0x55b5a6e57240] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'out.aac':
  Duration: 00:49:48.09, bitrate: 87 kb/s
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 87 kb/s
At least one output file must be specified

    ~/workspace/fleet/whisper ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── INT ✘  base   at 03:05:39  
❯ insanely-fast-whisper --file-name out.aac --flash True
You are attempting to use Flash Attention 2.0 with a model initialized on CPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1:52:08
Voila! Your file has been transcribed go check it out over here! output.json

    ~/workspace/fleet/whisper ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── took 1h 52m 53s   base   at 04:58:34  
```

**Comment by Vaibhavs10** [comment]
Hi @mikeyang01 - The 1-minute time includes downloading the model (when used for the first time), initialising it and preparing it for Flash attention/ Better Transformer, preparing the audio, and finally transcribing.

The time that we track for benchmarks is only for generations since the rest would be quite small for long audios anyway.

I hope that helps clear out the confusion.

**Comment by Vaibhavs10** [comment]
Hi @james-curtis - I'm not 100% sure but there's something definitely wrong with the environment. Ideally with the default arguments, you should get a OOM since the default `batch-size` is `24` which would mean roughly `13-14GB` VRAM utilisation.

Can you try a fresh installation after power-cycling your GPU?

**Comment by james-curtis** [comment]
> Hi @james-curtis - I'm not 100% sure but there's something definitely wrong with the environment. Ideally with the default arguments, you should get a OOM since the default `batch-size` is `24` which would mean roughly `13-14GB` VRAM utilisation.
> 
> Can you try a fresh installation after power-cycling your GPU?

Sorry, I didn't re-use insanely-fast-whisper, because I admit that I don't have such a large amount of video memory on my machine, and even if it runs successfully, it will be slower due to frequent memory swapping. Anyway, thank you and the project team for your time.

**Comment by mikeyang01** [comment]
> Hi @mikeyang01 - The 1-minute time includes downloading the model (when used for the first time), initialising it and preparing it for Flash attention/ Better Transformer, preparing the audio, and finally transcribing.
> 
> The time that we track for benchmarks is only for generations since the rest would be quite small for long audios anyway.
> 
> I hope that helps clear out the confusion.
Thanks for the reply, 
I would like to use it for realtime voice to text.
is it possible to use it to ASR small size audio in realtime?
thanks
