### ISSUE TITLE
CPU based insanely fast whisper

### ISSUE THREAD

**Issue by Tortoise17** [Vaibhavs10/insanely-fast-whisper#125]
Dear Friends, 

is there any update or hope to have CPU based insanely fast whisper? Please guide.

**Comment by Vaibhavs10** [comment]
I put a comment here about a possible next step: https://github.com/Vaibhavs10/insanely-fast-whisper/pull/150#issuecomment-1878631911

(closing this, as this will likely take some time).

**Comment by DakeQQ** [comment]
Feel free to explore this [repository](https://github.com/DakeQQ/Transcribe-and-Translate-Subtitles), designed specifically for CPU-only users. With an Intel i3-12300 CPU (4 threads), it can transcribe a 2-hour movie in approximately 20 minutes using Whisper-Large-V3, and 10 minutes for SenseVoiceSmall model. Additionally, it includes multiple denoisers and VADs to enhance subtitle quality.
