### ISSUE TITLE
Running from source on M3 gives a torch wrong binary installed

### ISSUE THREAD

**Issue by byjlw** [Vaibhavs10/insanely-fast-whisper#126]
I've tried many things to fix this but no luck. I this package via brew install but running from source gives me this error. 
I've used an environment and installed torch specifying the right package but still get this issue. 
```
$ conda update conda

$ conda create -n M3Max  python=3.8

$ conda activate M3Max

$ conda install -y clang_osx-arm64 clangxx_osx-arm64 gfortran_osx-arm64

$ MACOSX_DEPLOYMENT_TARGET=14.1 CC=clang CXX=clang++ python -m pip --no-cache-dir   install torch torchvision torchaudio

$ python -c "import torch; print(torch.__version__)"  #---> (Confirm the version is 1.11.0)

$ MACOSX_DEPLOYMENT_TARGET=14.1 CC=clang CXX=clang++ python -m pip --no-cache-dir  install  torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cpu.html

$ MACOSX_DEPLOYMENT_TARGET=14.1 CC=clang CXX=clang++ python -m pip --no-cache-dir  install  torch-sparse -f https://data.pyg.org/whl/torch-2.1.0+cpu.html

$ MACOSX_DEPLOYMENT_TARGET=14.1 CC=clang CXX=clang++ python -m pip --no-cache-dir  install  torch-geometric
```

Issue
-------

`OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib, 0x000A): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

**Comment by Vaibhavs10** [comment]
Hey @byjlw - this looks like a M3 specific issues, I'm not sure Torch supports M3 fully at the moment? Were you able to fix it in the end?

**Comment by byjlw** [comment]
Torch works on M3. Dependencies just need to account for it since it requires the right torch binaries. If I brew install and run the package (not from source) using the MPS flag things work. I just can't run from source due to dependency hell

**Comment by Vaibhavs10** [comment]
Ah! @byjlw - This could be because of the Python version too, Since Optimum doesn't support Python 3.12 at the moment. This could be because of it.

(I'm going to close the issue since it worked out in the end, however, feel free to re-open this) 🤗
