### ISSUE TITLE
Can't install versions > 0.0.8 due to wrong python version even when Python 3.11.6 is installed

### ISSUE THREAD

**Issue by rklasen** [Vaibhavs10/insanely-fast-whisper#143]
Hi, first and foremost thank you for this awesome implementation. I've already used you demo code without the cli for (quite literally) hundreds of hours of audio.

So the issue is, I can't install the package itself with pip or pipx because it won't find the correct python version. Simply installing with

```
pipx install insanely-fast-whipser
```

Does work, but the version won't actually work (new BetterTransformers, differenct closed issue). I've then realized that pipx installs 0.0.8 but nothing newer. Forcing a new version with

```
pipx install insanely-fast-whisper==0.0.13
```

Doesn't work, with the error:

```
Fatal error from pip prevented installation. Full pip output in file:
    /home/remus/.local/pipx/logs/cmd_2023-12-16_12.34.56_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python <=3.11,>=3.8; 0.0.11 Requires-Python <=3.11,>=3.8; 0.0.12 Requires-Python <=3.11,>=3.8; 0.0.13 Requires-Python <=3.11,>=3.8; 0.0.9 Requires-Python <=3.11,>=3.8
    ERROR: Could not find a version that satisfies the requirement insanely-fast-whisper==0.0.13 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5b0, 0.0.5b1, 0.0.5b2, 0.0.5b3, 0.0.5, 0.0.6, 0.0.7, 0.0.8)
    ERROR: No matching distribution found for insanely-fast-whisper==0.0.13

Error installing insanely-fast-whisper from spec 'insanely-fast-whisper==0.0.13'.
```

But the python version is:

```
python --version                          
Python 3.11.6
```

---

So it looks like either pipx won't parse the version correctly, or it treats 3.11.6 as > 3.11.

The issue can be worked around by passing the `--ignore-requires-python` flag to pip.

```
pipx install insanely-fast-whisper==0.0.13 --force --pip-args="--ignore-requires-python"
```

I don't know if this can be fixed by requiring version `< 3.12` (instead of `<=3.11`), but maybe the workaround helps someone else.

**Comment by Vaibhavs10** [comment]
ooooh! that's a lovely find! would you open to add this information as in the README please? 🙏

**Comment by rklasen** [comment]
Sure, I'll prepare a PR.
