### ISSUE TITLE
Missing option to provide a prompt argument

### ISSUE THREAD

**Issue by hlevring** [Vaibhavs10/insanely-fast-whisper#155]
Would be really valuable to have the option to add --initial_prompt argument 
https://platform.openai.com/docs/guides/speech-to-text/prompting

**Comment by Vaibhavs10** [comment]
Hi @hlevring - Thanks for your issue and sorry for the delay in responding to you here. Currently we do not support it as mentioned here: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/25

However, you can do so with vanilla transformers like this: https://github.com/huggingface/transformers/issues/27317#issuecomment-1849398973

(closing this issue for now, feel free to re-open it if you have follow-up questions.)
