### ISSUE TITLE
Is it available for Commercial Use?

### ISSUE THREAD

**Issue by souvikqb** [Vaibhavs10/insanely-fast-whisper#17]
I am truly impressed with the remarkable work on this project. 

I am interested in understanding whether this model is accessible for commercial applications. Could you please provide more details on the commercial usage terms and conditions?

Thanks

**Comment by Vaibhavs10** [comment]
Yes! -> These are optimisations built on top of openai/whisper -> so same license and usage restrictions apply.
INAL, but you can use it for commercial purposes.
