### ISSUE TITLE
List of input parameters currently supported?

### ISSUE THREAD

**Issue by souvikqb** [Vaibhavs10/insanely-fast-whisper#18]
Hi 

Thanks for this awesome repository!

I wanted to learn what parameters are you currently supporting.

Thanks

**Comment by Vaibhavs10** [comment]
Hi @souvikqb - You can find all the parameters listed here: https://github.com/Vaibhavs10/insanely-fast-whisper/blob/bc242891b2dae1b46e02825b1616f00714427f18/transcribe.py#L8

Alternatively, just run, `python transcribe.py --help`

Closing this for now, feel free to re-open if you have any other questions!

**Comment by souvikqb** [comment]
Any idea when you guys will be rolling out support for srt, word and verbose output format?

**Comment by Vaibhavs10** [comment]
Hey @souvikqb - Unfortunately, we won't, but more than happy to review a PR adding that.
