### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by geoHeil** [Vaibhavs10/insanely-fast-whisper#2]
thanks for the example!

can you add a translation example?

**Comment by Vaibhavs10** [comment]
Hi there, for translation, you'd just need to pass `task='translate'`, and it should work out of the box! 🤗

**Comment by geoHeil** [comment]
but does this also work for non-audio text-only input? Or would I need to feed this somehow on the prompt?

**Comment by Vaibhavs10** [comment]
This doesn't work on `text` it only works for audio. However, there are plenty, text-only models on the hub: https://huggingface.co/models?pipeline_tag=translation&sort=trending

**Comment by Vaibhavs10** [comment]
Closing this for now, feel free to re-open if you have any further queries! 🤗

**Comment by myusf01** [comment]
I couldn't get translation to work by just changing `"task" : "translate"` it still returns with output just like transcribe.
How should I specify which language to translate?
