### ISSUE TITLE
ValueError : The generation config is outdated

### ISSUE THREAD

**Issue by vatsaldin** [Vaibhavs10/insanely-fast-whisper#20]
![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/1464312/af312200-ffab-4804-a84e-935d64e9f080)

![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/1464312/3dd7c1a6-1ba2-4e15-b900-231b189445ee)

**Comment by Vaibhavs10** [comment]
Hi @vatsaldin - It appears your `transformers` version is outdated. Can you try and run `pip install --upgrade transformers`?
