### ISSUE TITLE
ValueError : The generation config is outdated

### ISSUE THREAD

**Issue by vatsaldin** [Vaibhavs10/insanely-fast-whisper#22]
Hi @Vaibhavs10 

I forgot to mention that I had changed the model from large-v2 to openai/whisper-medium.en

Does it mean that at present implementation supports large-v2 only?

I changed it back to the same and right now and that error did not come and it has started downloading model weights (6 GB).

![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/1464312/0076cdb1-d24f-41a7-833b-6fb2ded12abd)

**Comment by Vaibhavs10** [comment]
Hi @vatsaldin - You're indeed correct, this is an issue on our end. I'll inform you here as soon as we fix this.

For all intents and purposes, I'll recommend using `large-v2` btw.
