### ISSUE TITLE
Performing speaker diarization without CLI?

### ISSUE THREAD

**Issue by sidharthrajaram** [Vaibhavs10/insanely-fast-whisper#240]
Hi, big fan of the project. Transcription and diarization works pretty great from CLI. Is there a way to perform speaker diarization without CLI?

**Comment by sidharthrajaram** [comment]
Update: Was able to achieve this based on the existing implementation at https://github.com/Vaibhavs10/insanely-fast-whisper/blob/main/src/insanely_fast_whisper/cli.py

**Comment by JorgeBernalll** [comment]
@sidharthrajaram how did you set the hf-token without CLI?
