### ISSUE TITLE
does it support initial_prompt?

### ISSUE THREAD

**Issue by silvacarl2** [Vaibhavs10/insanely-fast-whisper#25]
does it support initial_prompt?

this looks incredible.

**Comment by Vaibhavs10** [comment]
Hi @silvacarl2 - Could you elaborate on what behaviour would you like to test?

**Comment by Vaibhavs10** [comment]
Hi @silvacarl2 - Currently the way the CLI is structured it doesn't. We'd need to wait a bit (a month) to get it to the latest release of Transformers. 

(Closing this issue for now, I'll re-open it when we have a new release)
