### ISSUE TITLE
what's faster whisper here?

### ISSUE THREAD

**Issue by lucasjinreal** [Vaibhavs10/insanely-fast-whisper#26]
It's ctranslate2?

**Comment by Vaibhavs10** [comment]
Sorry! What's your question here?

If you're talking about how this is fast?, then that is due to the `transformers` backend + BetterTransformer API by PyTorch.

**Comment by lucasjinreal** [comment]
there is another faster-whisper repo out there, based on ctranslate2, am not sure which inference lib you are using

**Comment by Vaibhavs10** [comment]
We use `Transformers` for Inference: https://github.com/huggingface/transformers

**Comment by lucasjinreal** [comment]
@Vaibhavs10 Hi, transformers is just a wrapper of pytorch, how does you faster than openai-whisper by inference on same backend?
