### ISSUE TITLE
Does it / will it support large-v3? 

### ISSUE THREAD

**Issue by dgoryeo** [Vaibhavs10/insanely-fast-whisper#29]
Hi @Vaibhavs10 , just came across your repository, love the name. 
Is the large-v3 already supported, or would it need to construct/tranform the new model? 
Thanks
PS. there was no discusison tab so I used the issues tab. Hope you don't mind.

**Comment by Vaibhavs10** [comment]
Hi @dgoryeo - It should support it by end of day today or maximum tomorrow! 🤗

**Comment by Vaibhavs10** [comment]
It now does! 🔥 
https://x.com/reach_vb/status/1723810943329616007?s=20

**Comment by dgoryeo** [comment]
@Vaibhavs10 , good stuff. I noticed your note on GPU compatibility. I have a nvidia rtx3060, it should be compatible, right?
