### ISSUE TITLE
Any chance of a CPU implementation?

### ISSUE THREAD

**Issue by Evilmaax** [Vaibhavs10/insanely-fast-whisper#3]
Any chance to get a CPU implementation in near future?

**Comment by Vaibhavs10** [comment]
Intel has nice CPU implementation which works brilliantly!: https://huggingface.co/Intel/whisper-large-v2-onnx-int4
Do take it out for a spin!

I'm closing this issue for now, but feel free to re-open if you have any questions! 🤗

**Comment by DakeQQ** [comment]
@Evilmaax 
Feel free to explore this [repository](https://github.com/DakeQQ/Transcribe-and-Translate-Subtitles), designed specifically for CPU-only users. With an Intel i3-12300 CPU (4 threads), it can transcribe a 2-hour movie in approximately 20 minutes using Whisper-Large-V3, and 10 minutes for SenseVoiceSmall model. Additionally, it includes multiple denoisers and VADs to enhance subtitle quality.
