### ISSUE TITLE
Can whisper support fast audio transcribing in real time

### ISSUE THREAD

**Issue by 1926627357** [Vaibhavs10/insanely-fast-whisper#35]
I noticed that someone mentioned  the first token latency in streaming mode in https://twitter.com/arpagon/status/1723858496733511851. Therefore, I'm very curious whether if whisper can support fast auto transcribing in real time.

**Comment by Vaibhavs10** [comment]
Planned for the upcoming release: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/46
