### ISSUE TITLE
Support for CPU Mode

### ISSUE THREAD

**Issue by heyimjonas** [Vaibhavs10/insanely-fast-whisper#36]
It would be nice to see support for a cpu mode! :)

**Comment by Vaibhavs10** [comment]
Planned for the upcoming release: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/46

**Comment by DakeQQ** [comment]
@heyimjonas 
Feel free to explore this [repository](https://github.com/DakeQQ/Transcribe-and-Translate-Subtitles), designed specifically for CPU-only users. With an Intel i3-12300 CPU (4 threads), it can transcribe a 2-hour movie in approximately 20 minutes using Whisper-Large-V3, and 10 minutes for SenseVoiceSmall model. Additionally, it includes multiple denoisers and VADs to enhance subtitle quality.

**Comment by Hasan-Naseer** [comment]
> @heyimjonas Feel free to explore this [repository](https://github.com/DakeQQ/Transcribe-and-Translate-Subtitles), designed specifically for CPU-only users. With an Intel i3-12300 CPU (4 threads), it can transcribe a 2-hour movie in approximately 20 minutes using Whisper-Large-V3, and 10 minutes for SenseVoiceSmall model. Additionally, it includes multiple denoisers and VADs to enhance subtitle quality.

wait is this only for videos or can you do .wav files as well? I mean, why shouldn't it be for just audio when they can do it on movies, they can on audio too, but I'm just confused, why haven't they advertised it as such?

**Comment by DakeQQ** [comment]
@Hasan-Naseer 
This project uses the Python package `pydub` to load the input file, which supports common video formats such as `.mp4`, `.mkv`, etc., and audio formats such as `.mp3`, `.wav`, etc.
