### ISSUE TITLE
Flash Attention issue

### ISSUE THREAD

**Issue by mediarl** [Vaibhavs10/insanely-fast-whisper#38]
Hi,

Thanks for this repo. It works great. I am just not able to make Flash Attention works. I have a RTX 3090 so it's supposed to work based on their documentation.

I followed the instructions and everything is installed as expected:
```
pip install flash-attn --no-build-isolation
```
I can import the Flash Attention dependencies:
```
python -c "from flash_attn import flash_attn_qkvpacked_func, flash_attn_func"
```

But when I try to run `insanely-fast-whisper` with `Flash=True`, I get this error:
```
$ insanely-fast-whisper --file-name audio.mp3 --language fr --flash True
Traceback (most recent call last):
  File "/home/romain/.local/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
  File "/home/romain/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 78, in main
    pipe = pipeline(
  File "/home/romain/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 870, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/romain/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/romain/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/romain/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3233, in from_pretrained
    config = cls._check_and_enable_flash_attn_2(config, torch_dtype=torch_dtype, device_map=device_map)
  File "/home/romain/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1273, in _check_and_enable_flash_attn_2
    raise ImportError(
ImportError: Flash Attention 2 is not available. Please refer to the documentation of https://github.com/Dao-AILab/flash-attention for installing it. Make sure to have at least the version 2.1.0
```

**Comment by mediarl** [comment]
I was able to make it work using the Python script.

Note: Using the 5 hours audio with my RTX3090, it only took 88 seconds 👍

**Comment by omarsiddiqi224** [comment]
@mediarl How were you able to make it work? Could you possibly share your code?

**Comment by li-yifei** [comment]
@omarsiddiqi224 Hey, I've figured out this and it may help you too.
Since insanely-fast-whisper is installed into pipx managed venv, we should install `flash-attn` into the env too.

If you can just run `pip install flash-attn --no-build-isolation` without building errors, then you can try
``` Bash
$ pipx runpip insanely-fast-whisper install flash-attn --no-build-isolation
```
That could install the flash-attn inside the venv

**Comment by Vaibhavs10** [comment]
Hey all! We're trying to find the best way to package the `flash-attn` library at the moment.
However given it requires a specific build it is difficult to make it work. What you can do however is setup the environment locally and run via the following gist: https://gist.github.com/Vaibhavs10/16087d3c4dea59bdcba07ffbeee91272

You should then be able to run `python insanely-fast-whisper.py --file-name <FILE NAME OR URL>`

**Comment by Vaibhavs10** [comment]
Leaving this issue open till this workaround is not showcased on the README.

**Comment by Vaibhavs10** [comment]
This is now part of the [FAQs](https://github.com/Vaibhavs10/insanely-fast-whisper#frequently-asked-questions). Hence, closing this! Thank you all!

**Comment by sadimoodi** [comment]
> @omarsiddiqi224 Hey, I've figured out this and it may help you too. Since insanely-fast-whisper is installed into pipx managed venv, we should install `flash-attn` into the env too.
> 
> If you can just run `pip install flash-attn --no-build-isolation` without building errors, then you can try
> 
> ```shell
> $ pipx runpip insanely-fast-whisper install flash-attn --no-build-isolation
> ```
> 
> That could install the flash-attn inside the venv

this is not working on windows, i keep getting this error: "flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available? "
