### ISSUE TITLE
How is the VRAM usage?

### ISSUE THREAD

**Issue by tahaygun** [Vaibhavs10/insanely-fast-whisper#4]
Hi there, the project looks really neat. Congrats and thanks! I am curious if this one is also as VRAM efficient as the fast-whisper? I couldn't see anything regarding that in the readme.

**Comment by Vaibhavs10** [comment]
Closing this for now, feel free to re-open if you have more questions! 🤗

**Comment by tahaygun** [comment]
Sure, thanks a lot for the information @Vaibhavs10 .
