### ISSUE TITLE
Segments

### ISSUE THREAD

**Issue by omarsiddiqi224** [Vaibhavs10/insanely-fast-whisper#43]
does the output have segments, the same way model.transcribe() does in the original model?

`import torch
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition",
                "openai/whisper-large-v2",
                torch_dtype=torch.float16,
                device="cuda:0")

pipe.model = pipe.model.to_bettertransformer()

outputs = pipe("<FILE_NAME>",
               chunk_length_s=30,
               batch_size=24,
               return_timestamps=True)

**outputs["segments"]**`

**Comment by Vaibhavs10** [comment]
outputs["timestamps"] would have the corresponding timestamped segments. I hope that answers your question!
