### ISSUE TITLE
TLDR numbers right?

### ISSUE THREAD

**Issue by fofr** [Vaibhavs10/insanely-fast-whisper#44]
> TL;DR - Transcribe 300 minutes (5 hours) of audio in less than 98 seconds - with [OpenAI's Whisper Large v3](https://huggingface.co/openai/whisper-large-v3). Blazingly fast transcription is now a reality!⚡️

Based on the benchmarks table the fastest 98s corresponds to 150 minutes of audio, this is also what's in the colab and what was tweeted: https://twitter.com/reach_vb/status/1723810943329616007

Is the 300 a typo? Or was it a different benchmark/hardware?

**Comment by Vaibhavs10** [comment]
You are indeed correct! That is my bad. The 300 with 98 seconds was a benchmark on A100 (80GB) with 96 batch size + flash attention.

It was purely to get the maximum possible ceiling for the transformers' implementation. Let me fix this.

**Comment by Vaibhavs10** [comment]
For book-keeping to transcribe 300 minutes in 98 seconds, here's what I did.

`python cli.py --file-name <FILE NAME or URL> --batch-size 96 --flash True` (ran it on a A100, averaged the score across 3 runs)

**Comment by fofr** [comment]
🙌 Thank you for clarifying
