### ISSUE TITLE
Upcoming in next release! (this week)

### ISSUE THREAD

**Issue by Vaibhavs10** [Vaibhavs10/insanely-fast-whisper#46]
- [ ] Speaker Diarization with Pyannote 🤯 
- [ ] Fast CPU support 💻 
- [ ]  Streaming ⚡

**Comment by thomasmol** [comment]
Awesome! I have a pyannote implementation here https://github.com/thomasmol/replicate-whisper-diarization if you want to take a look.
Also really curious how streaming would work!

**Comment by omarsiddiqi224** [comment]
There is this resource as well to help with diarization: https://github.com/MahmoudAshraf97/whisper-diarization

**Comment by zeke** [comment]
Looking forward to diarization 🙏🏼

**Comment by Juergen-J-F** [comment]
Hi, is testing CPU possible already? Would be greatly interested to compare it to faster-whisper. Also, what would the limitations be? Batching should work? Flash attention? Your speeds sound really promising.

**Comment by souvikqb** [comment]
> * [ ]  Speaker Diarization with Pyannote 🤯
> * [ ]  Fast CPU support 💻
> * [ ]   Streaming ⚡

Hey 👋 any update on these releases. They would open up a lot of possibilities

**Comment by akashAD98** [comment]
this is alos not supporting on linux cpu machine uabntu 22.04,python 10 installed

```
import datetime
import re
from faster_whisper import WhisperModel

model_size = "large-v2"

# Initialize the model for GPU with FP16
model = WhisperModel(model_size, device="cpu", compute_type="int8")

# Transcribe the audio file
segments, info = model.transcribe(
    "/home/samplewhisper1.mp3", beam_size=1)

# Open a text file in write mode
with open("transcription_sample.txt", "w") as file:
    # Write the detected language and its probability
    # file.write("Detected language '{}' with probability {}\n".format(info.language, info.language_probability))

    # Write each segment of the transcription
    for segment in segments:
        file.write(
            "[{:.2f}s -> {:.2f}s] {}\n".format(segment.start, segment.end, segment.text))


print("done finishedd -->>")

```


getting error 

```
Traceback (most recent call last):
  File "/home/akash/Projects/mango-ai/playground/whisperx_audio/instantly_faster_1.py", line 3, in <module>
    from faster_whisper import WhisperModel
  File "/home/akash/Projects/mango-ai/playground/whisperx_audio/faster_whisper.py", line 4, in <module>
    from faster_whisper import WhisperModel
ImportError: cannot import name 'WhisperModel' from partially initialized module 'faster_whisper' (most likely due to a circular import) (/home/akash/Projects/mango-ai/playground/whisperx_audio/faster_whisper.py)

```

**Comment by acul3** [comment]
Looking forward to this 

Btw @Vaibhavs10 have you consider adding vad(voice activity detection) to the pipeline

By my testing..VAD reduce hallucination espscially with audio lot of silence and noise

Thanks

**Comment by BBC-Esq** [comment]
Might I suggest using nemo toolkit instead?  It seems to avoid pyannote's requirement of using a huggingface key or what not to access their model.  [omarsiddiqi224](https://github.com/omarsiddiqi224)  is the one who posted a link to a repository that relies on it instead of pyannote.

**Comment by bluusun** [comment]
How can the speaker diarization be used? Where does it show? Thanks for adding this!

**Comment by TomExMachina** [comment]
Does anyone have a streaming script or snippet they can share ahead of the release? If you do I will help iterate on it.

**Comment by Vaibhavs10** [comment]
Hey @bluusun - Currently, the API is a bit spaghetti, however, if you pass a parameter `--hf_token <HF token>` it should automatically diarise.

@kadirnar recently made a PR to make this more clear https://github.com/Vaibhavs10/insanely-fast-whisper/pull/83 (we'll make a release tomorrow or on saturday along with some more goodies 🤞 )

**Comment by Vaibhavs10** [comment]
@BBC-Esq - I'm opening a new issue to discuss this https://github.com/Vaibhavs10/insanely-fast-whisper/issues/85, I think adding support for Nvidia NeMo might make sense and give people the option to choose different backends too.

**Comment by Vaibhavs10** [comment]
(Closing this issue since the release already happened; we need another patch (to fix the current API) before considering the next steps.)

**Comment by Tortoise17** [comment]
@Vaibhavs10 CPU usage is now possible with the new release?

**Comment by Tortoise17** [comment]
@Vaibhavs10 Fast CPU support was also mentioned to make available in this release in addition to diarization and streaming

**Comment by Vaibhavs10** [comment]
Let's discuss that in a seperate issue. (I'll open one)

**Comment by DakeQQ** [comment]
@JuergenFleiss 
Feel free to explore this [repository](https://github.com/DakeQQ/Transcribe-and-Translate-Subtitles), designed specifically for CPU-only users. With an Intel i3-12300 CPU (4 threads), it can transcribe a 2-hour movie in approximately 20 minutes using Whisper-Large-V3, and 10 minutes for SenseVoiceSmall model. Additionally, it includes multiple denoisers and VADs to enhance subtitle quality.
