### ISSUE TITLE
Support for more file types

### ISSUE THREAD

**Issue by sagar-kris** [Vaibhavs10/insanely-fast-whisper#48]
support various file types including video like .mov, .mp4, etc. this is easily achievable via a number of python packages.

example implementation:

`!pip install moviepy`

`import moviepy.editor as mp`
`clip = mp.VideoFileClip("/path/to/video/file.ext")`
`clip.audio.write_audiofile("/path/to/video/file.mp3")`

**Comment by Vaibhavs10** [comment]
Hi @sagar-kris - I'd like to keep the codebase clean and simple.

@patrick91 wdyt about adding such a thing? I feel this step should be run independently by the user and we should only focus on accepting audio.

**Comment by patrick91** [comment]
I think we should consider it in future, for now we can put a tipo on how to convert things with FFmpeg 😊

**Comment by sagar-kris** [comment]
thanks for the quick response, happy to open a simple PR for this.

I also noticed errors when trying to run it on .m4a files (which is an audio format). would you consider either a conversion or natively supporting it?

**Comment by Vaibhavs10** [comment]
Hi @sagar-kris - What's the error you get with a `.m4a` format?
I want to pause preprocessing related features till we add speaker diarization. Once that is in-place, we can get the ball rolling is that okay?

**Comment by akashAD98** [comment]
!pip install ffmpeg     # for linux  
& run below code ffmpeg
```
ffmpeg -i video.mp4 audio.wav
```

**Comment by akashAD98** [comment]
> Hi @sagar-kris - What's the error you get with a `.m4a` format? I want to pause preprocessing related features till we add speaker diarization. Once that is in-place, we can get the ball rolling is that okay?

when should we expect this feature?? i tried whisperx for diallation & able to do it using your repo. but i think your planning to add direct support for this right?

**Comment by Vaibhavs10** [comment]
(closing this - since it is not on the cards atm)
