### ISSUE TITLE
[brainstorming] Torch.mps backend speedup! 

### ISSUE THREAD

**Issue by sagar-kris** [Vaibhavs10/insanely-fast-whisper#49]
enable support for mps so this can be run natively on apple silicon. when run with `device="mps"` instead of `device="cuda:0"`, the error as shown in the error log below occurs. clearly this is lacking in the underlying pytorch implementation, so we can use this issue to comment on the [pytorch issue](https://github.com/pytorch/pytorch/issues/77764) and garner addition support.

error log:

> Traceback (most recent call last):
>   File "./insanely-fast-whisper/whisper.py", line 15, in <module>
>     outputs = pipe("/path/to/audio/file.mp3",
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
>     return super().__call__(inputs, **kwargs)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1132, in __call__
>     return next(
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
>     item = next(self.iterator)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 266, in __next__
>     processed = self.infer(next(self.iterator), **self.params)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
>     model_outputs = self._forward(model_inputs, **forward_params)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 555, in _forward
>     encoder_outputs=encoder(inputs, attention_mask=attention_mask),
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/transformers/models/whisper/modeling_whisper.py", line 1159, in forward
>     layer_outputs = encoder_layer(
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "./insanely-fast-whisper/lib/python3.10/site-packages/optimum/bettertransformer/models/encoder_models.py", line 1039, in forward
>     hidden_states = torch._transformer_encoder_layer_fwd(
> NotImplementedError: The operator 'aten::_transformer_encoder_layer_fwd' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

**Comment by Vaibhavs10** [comment]
cc: @pcuenca for mps awareness.

@sagar-kris - would you like to make a list of unimplemented ops?

**Comment by pcuenca** [comment]
Hi @sagar-kris, thanks for letting us know! I'm curious if you checked whether it works without the call `to_bettertransformer()`, and how fast it'd be in that case. If it works, I wonder if the speed is better than using the CPU fallback for this op.

**Comment by sagar-kris** [comment]
a bit tight on time this week, but in a few days I can go ahead and
* document a list of unimplemented ops
* test `mps` with removing the call `to_bettertransformer()`
* run some simple `timeit` benchmarking tests

**Comment by Vaibhavs10** [comment]
We have preliminary support for Mac now! I'd love to figure out ways to make it faster without moving to a different backend than PyTorch.
Any ideas @pcuenca @sagar-kris ?
