### ISSUE TITLE
[feat] CLI Tool

### ISSUE THREAD

**Issue by ochen1** [Vaibhavs10/insanely-fast-whisper#5]
These optimizations are fantastic. To make it more accessible and user-friendly for those who prefer command-line tools, someone should consider developing a CLI (Command Line Interface) version of this project. This would greatly enhance the ease of use and automation for many users.

**Comment by Vaibhavs10** [comment]
I was recommended [Typer](https://typer.tiangolo.com). Let me know how it goes 🤗

**Comment by Vaibhavs10** [comment]
Feel free to open a PR. We can work on this together! @ochen1

**Comment by ochen1** [comment]
Hey I made this, https://github.com/ochen1/insanely-fast-whisper-cli

Can you check it out?

**Comment by Vaibhavs10** [comment]
Would you consider moving this to here? I'm happy to add you to the repo as a co-owner?
We'd potentially release a few more things + models in the days/ weeks to come! - this would include updates to the pipeline.

I'm ofc also happy if you would like to keep it as a repo under your namespace too!

**Comment by ochen1** [comment]
Hey, I originally wanted to use this as a project for my computer science course, but I guess I'd be okay with finding other ideas to pursue. How does co-ownership work? Do you want to create a GitHub organization for this?

**Comment by Vaibhavs10** [comment]
Hey hey! @ochen1 - No worries at all. Actually I think it is a much better idea to have a separate repo! I will ping you whenever I have new updates (so you can merge them upstream) 🤗 

I'd also like to tweet your project out! Do you have a twitter account? :)

Fantastic job with this!! You're awesome!

**Comment by Lhun** [comment]
I would love to add that this is an incredibly good idea and I was going to make the same suggestion. 
Most people who use whisper today use it entirely offline, outside of collabs and on their local machines. Personally, I use it almost purely in windows: 

`whisper --task Translate --device=cuda --model large-v2 --language Japanese `

If this project was a straight upgrade for that workflow, like a path variable replacement for whisper to something like 
`whisperbutfast --task Translate --device=cuda --model large-v2 --language Japanese`

it would be a massive boon to the community and to people who have made integrations with local interfaces and custom application workflows.

**Comment by ochen1** [comment]
Hi @Vaibhavs10 I do not use Twitter often. However, I've requested to connect with you on LinkedIn. I'm glad you like the idea! I actually also made one for [guillaumekln/faster-whisper](https://github.com/guillaumekln/faster-whisper) but never ended up publishing it. Hopefully my CLI tool will help someone 💪

**Comment by ochen1** [comment]
There is still a lot of work that needs to be done on this tool, as I have only done minimal testing so far. The project could also benefit from better documentation, additional features, and error-checking of user-supplied inputs. It would be nice if you could mention it on the README in case anyone else is interested in helping develop. I plan on making a Google Colab to demonstrate / for people to use this program as well.
