### ISSUE TITLE
whisper-large-v2 with flash attention 

### ISSUE THREAD

**Issue by bchinnari** [Vaibhavs10/insanely-fast-whisper#50]
I have very big list (~1M) of audio files and I would like to transcribe them using whisper-large-v2 and flash attention.

I am running it on A100 GPU  with the help of HF pipeline() funcitonality.
 
I felt the decoding is very slow and I would like to ask if my code has any issues
```
import torch
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition",
                "openai/whisper-large-v2",
                torch_dtype=torch.float16,
                model_kwargs={"use_flash_attention_2": True},
                generate_kwargs = {"language":"<|es|>","task": "transcribe"},
                device="cuda:0")
audioListPath="wav_audio2_16k_utts.list" ## list of audio files

audioListFP = open(audioListPath)
audioListL = audioListFP.readlines()
audioListL = [audio.strip("\n") for audio in audioListL]
total = len(audioListL)

outTxt = open("wav_audio2_esHyp_whisperlargeV2.txt","w") ## writing transcription to this file
s= 0
while s < total:
    e = s+50000
    print("---- decoding {}, {} ---".format(s,e) )
    batchUtts = audioListL[s:e]
    outputs = pipe(batchUtts, chunk_length_s=30, batch_size=50)  
    for output in outputs:
        outTxt.write(output['text']+"\n")
    s = e
```

When I run the above script I see one warning as follows
`You are attempting to use Flash Attention 2.0 with a model initialized on CPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.`

Hence, I am asking if I am using the model and the pipeline properly .
Help is appreciated

**Comment by bchinnari** [comment]
The warning about flush attention doesn't mean anything??

**Comment by bchinnari** [comment]
Yes, the input audio size really varies

**Comment by Vaibhavs10** [comment]
Please ignore the warning. It works fine out of the box.
The decoding will be slow if the audio lengths in the same batch vary greatly.

You can probably try to sort the audio files in a batch by length and then pass it.

**Comment by Vaibhavs10** [comment]
(closing this for now - feel free to re-open)
