### ISSUE TITLE
What's this based on...not seeing sourcecode.

### ISSUE THREAD

**Issue by BBC-Esq** [Vaibhavs10/insanely-fast-whisper#51]
Hello,

I'm fascinated by this project, but I don't see any of the source code even though there's a "src" folder and you can install it on Pypi.  What is this based on?  I'm unable to replicate your test results saying that it's 6x faster than ```faster-whisper``` or what not?  Is this just faster-whisper with an increased ```batch_size``` or does it actually innovate something new?

You're making bold claims about its speed that I have not been able to verify so...

Thanks!  Always looking for latest and greatest.  I'd also like to know how you think it compares to the Jax implementation located here [https://github.com/sanchit-gandhi/whisper-jax](https://github.com/sanchit-gandhi/whisper-jax)

**Comment by BBC-Esq** [comment]
Thanks, I used the non-flash attention approach since I couldn't get flash attention v2 to install correctly...and I used a batch size of 1 to get a fair comparison with faster-whisper...and I did notice a 2x speedup compared...although, I did not have have a chance to manually compare the actual transcriptions to verify any quality differences.  Are you contending that it's just as accurate as well as the transcription itself being faster?  Also, any particular reason you don't release the source code?

But if I understand you correctly, it's faster than faster-whisper out of the box...not faster than the Jax implementation...but faster than Jax if the flash-attention v2 approach is used?

I modified your example as follows when doing my test:

```
pipe = pipeline("automatic-speech-recognition",
                "openai/whisper-large-v2",
                torch_dtype=torch.float32,
                device="cuda:0")

pipe.model = pipe.model.to_bettertransformer()

# Process the audio file
outputs = pipe("[REDACTED PATH FOR PRIVACY REASONS]",
               chunk_length_s=30,
               batch_size=1,
               return_timestamps=True)
```

**Comment by Vaibhavs10** [comment]
>  Are you contending that it's just as accurate as well as the transcription itself being faster? 

Transformers implementation matches one to one with openai/whisper. So I'm quite confident that the transcription is at the same level.

> Also, any particular reason you don't release the source code?

Our codebase is fully open source and licensed under Apache 2.0 - https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/modeling_whisper.py

> But if I understand you correctly, it's faster than faster-whisper out of the box...not faster than the Jax implementation...but faster than Jax if the flash-attention v2 approach is used?

Nope. It should be faster than Whisper-Jax (which Transformers implementation of Whisper using the JAX backend) since that implementation does not leverage Flash Attention yet.

**Comment by Vaibhavs10** [comment]
btw just a side note `and I used a batch size of 1 to get a fair comparison with faster-whisper`

The batching is a core part of what makes this implementation fast!

**Comment by BBC-Esq** [comment]
Right...and even the Jax implementation states that you get at least a 10x speedup with batching with approximately 1% max loss in WER so...not sure if Jax would still be faster if your guys' approach and Jax did a comparison with the same batch size...But I don't think Jax uses flash attention v2 so...I'm not doubting you.  And I'm not an expert on this so...

But with Ctranslate2-based "faster-whisper" beam size of 5 (default) and batch size of 1 with this implementation, I saw a 2x speedup.  So I guess it falls upon me to try a beam size of 1 for a true comparison...Very interesting though, thanks.  So ya'll are part of the same team at Huggingface as I understand it?  I've been seeing some problems with the release of large-v3, but that's another topic for another day.  lol

THANKS for the sourcecode, thought it was being obscured.

Lastly, you are not converting the models to a proprietary format are you (like with ctranslate2/faster-whisper)?  I mean, if you use torch dtype16, it converts in that sense, but not a proprietary converter like ctranslate2...I noticed that it just downloaded the vanilla model from Openai...

**Comment by BBC-Esq** [comment]
> btw just a side note `and I used a batch size of 1 to get a fair comparison with faster-whisper`
> 
> The batching is a core part of what makes this implementation fast!

That's kind of what I figured!

**Comment by Vaibhavs10** [comment]
Yeah! Sanchit and I work on the same team. We're just trying to maximise the available open source options :)

Btw, I have some old benchmarks with various setting in the `notebooks` section:
`faster-whisper` - https://github.com/Vaibhavs10/insanely-fast-whisper/blob/main/notebooks/infer_faster_whisper_large_v2.ipynb
`transformers` - https://github.com/Vaibhavs10/insanely-fast-whisper/blob/main/notebooks/infer_transformers_whisper_large_v2.ipynb

Re: issues with `large-v3` please feel free to open an issue in transformers and tag me. I'll look into it promptly! 

I'll close this issue now (feel free to re-open)

**Comment by BBC-Esq** [comment]
That's cool to know.  I've noticed cool work from him and now I've met you so...Let me ask you though, is the default behavior of your implementation (and if you know Jax's) a beam size of 1 or 5 or what?

**Comment by BBC-Esq** [comment]
It means a lot to get a knowledgeable response.  Appreciate your guys' hard work.  Issue closed!
