### ISSUE TITLE
Feature Request: Automatic Language Recognition

### ISSUE THREAD

**Issue by NuperSu** [Vaibhavs10/insanely-fast-whisper#56]
Could you add automatic language recognition, like the original Whisper has?

**Comment by renownedapp** [comment]
Very much needed as well. As of now, everything is automatically translated into english.

**Comment by Vaibhavs10** [comment]
Hi @NuperSu - Would the `--language` tag not work in your case? :)

**Comment by NuperSu** [comment]
> Hi @NuperSu - Would the `--language` tag not work in your case? :)

It would if there was an option `None` like whisper has:
```
  --language {af,...,zh,Afrikaans,...,Yoruba}
                        language spoken in the audio, specify None to perform language detection (default: None)
```
But I get an error with `insanely-fast-whisper --language None`
```
ValueError: Unsupported language: none.
```

**Comment by Vaibhavs10** [comment]
Thanks for confirming! I'll add this right now.

**Comment by Vaibhavs10** [comment]
You can test via a colab here too: https://github.com/Vaibhavs10/notebooks/blob/main/insanely_fast_whisper_colab.ipynb

(Closing this issue now, feel free to re-open!)
