### ISSUE TITLE
.srt/.txt files & Speaker Recognition

### ISSUE THREAD

**Issue by bluusun** [Vaibhavs10/insanely-fast-whisper#59]
Very nice speedup - easily 10x faster than Whisper.

Is there a way to have it output the .txt and .srt that Whisper delivers as well? Is there an easy conversion script from the output.json?

Also is there a way to recognize speakers i.e. Speaker 1 , Speaker 2?

**Comment by thomasmol** [comment]
The output of the model is indeed a json, so you can convert this to .txt or .srt or whatever you like with python, but you'd have to write your own script to do this. Plenty of tutorials on how to do this online!

Regarding recognizing speakers: that is called diarization, which Whisper in itself does not provide (yet?). Look at e.g. [pyannote audio](https://github.com/pyannote/pyannote-audio), which has an open-source model for diarization. You'd have to build your own script/pipeline to transcribe + diarize your audio.

**Comment by bluusun** [comment]
Thanks! Do you have an example search term to convert the output.json to txt/srt - seems to not find anything directly relevant.

**Comment by thomasmol** [comment]
Alright let me show you how I would do this:
First I'd try and find out what the output.json looks like, as in, what is its structure. You can do this by just running the model and looking at the output. It'll probably be something like this: 
```json
[
  {
    "text": "wow this is transcribed text"
    "start": 0.1
    "end": 0.3
  },
  // ... more objects like this
]
```
So it is an array of objects, and each object has attributes of text, start and end.
Converting this to .txt depends on what you'd want the .txt to look like, maybe you'd only need the text and want each segment or item to be on a newline. 

So you can write a script in python like this: 
```python
with open('output.txt', 'w') as file:
  for item in data:
    file.write(item['text'] + '\n')
```
where the output of the model is saved in the `data` variable.
You can Google for things like "python array of objects to txt file" and you'll probably find something. 
Or use something like ChatGPT or Phind to write it for you.
And you'd do the same for the .srt file type.

**Comment by akashAD98** [comment]
@bluusun @Vaibhavs10  ill add a code for speaker recognition ,ill make new pr for this

**Comment by bluusun** [comment]
> @bluusun @Vaibhavs10 ill add a code for speaker recognition ,ill make new pr for this

That would be incredible to have diarization included as well in 'fast whisper'!

**Comment by Vaibhavs10** [comment]
Hi @Tortoise17 - I work on this project over the weekends and outside of my day job. Finding time has been a challenge recently! I do have a working prototype ready now! I'll open up a PR soon so that we get that going!

Cheers & apologies for the delay!

**Comment by Tortoise17** [comment]
@Vaibhavs10 I can understand. and Heartly billions of thankyou for such a great work.

**Comment by bluusun** [comment]
> [<img alt="@Tortoise17" width="40" height="40" src="https://avatars.githubusercontent.com/u/36593708?s=80&amp;v=4">](/Tortoise17)
> ###

Thanks for contributing to this very promising repo!!!

**Comment by bluusun** [comment]
Thanks for adding speaker diarization!

Just ran with newest version from pip with -U (0.0.10) and newest transformers and no options but the filename. The output.json seems the same as before. 

How can I see the speaker diarization in output.json?
