### ISSUE TITLE
Passing parameters for whisper model inference results in unexpected keyword argument error

### ISSUE THREAD

**Issue by ravi0912** [Vaibhavs10/insanely-fast-whisper#6]
I am encountering an issue while attempting to pass parameters for the Whisper model inference using the code snippet below:

`outputs = pipe("audio.mp3", 
               chunk_length_s=30,
               batch_size=24,
               return_timestamps=True,
               condition_on_previous_text=trans["condition_on_previous_text"],
               vad_filter=True, 
               word_timestamps=True,
               repetition_penalty=trans["repetition_penalty"],
               temperature=trans["temperature"])
`

The code above is intended to perform inference using the Whisper model, but it results in the following error:
`TypeError: AutomaticSpeechRecognitionPipeline._sanitize_parameters() got an unexpected keyword argument 'condition_on_previous_text'.
`

**Comment by Vaibhavs10** [comment]
Hi @ravi0912 - Are you using this with `transformers`?
Can you paste the entirety of your full code-snippet?

**Comment by ravi0912** [comment]
This is resolved.

```python
generate_kwargs = {
    # "beam_size": 5,
    "language": 'en',
    "temperature": 0.2,
    "repetition_penalty": 3.0,
    # "condition_on_previous_text": True,
    "task": "transcribe"
}

outputs = pipe("audio.mp3", 
               chunk_length_s=30,
               batch_size=24,
               return_timestamps=True, generate_kwargs = generate_kwargs)
```
