### ISSUE TITLE
fasterwhisper and whisperx are faster than this repo

### ISSUE THREAD

**Issue by lucasjinreal** [Vaibhavs10/insanely-fast-whisper#60]
Hello, have u tested fasterwhisper and whisperx? https://github.com/guillaumekln/faster-whisper

this lib is way more faster than transformers.

**Comment by thomasmol** [comment]
I am sure he has. 
Please provide benchmarks comparing faster-whisper and insanely-fast-whisper that support your claim.

**Comment by patrick91** [comment]
also make sure to try with flash attention enabled 😊

**Comment by Vaibhavs10** [comment]
Thanks @thomasmol & @patrick91!
@lucasjinreal - We've put up some benchmarks on the [README](https://github.com/Vaibhavs10/insanely-fast-whisper#insanely-fast-whisper). I didn't get the time to benchmark WhisperX but given it uses `faster-whisper` backend, I'm assuming we're faster here.

I'm closing this issue for now, feel free to re-open if you have any questions!

**Comment by lucasjinreal** [comment]
So we tuning on hf's transformers like enable flashattn etc, and got faster speed than faster-whisper? Why so many people bother using ctranslate2 to do whisper if transformers got a faster speed?

**Comment by Vaibhavs10** [comment]
Because we added it 2 weeks back :)

**Comment by lucasjinreal** [comment]
If so, we need ask people stop using ctranslate2, it's really messy and very hard to install without pain.

**Comment by thomasmol** [comment]
@lucasjinreal we don't need to do anything. You are free to use this repo and stop using ctranslate. Maybe ctranslate has some other benefits or more improvements down the line that would improve its performance. Other people are free to use whatever library or tech they want, you don't have to "ask people to stop" using a certain library.

**Comment by lucasjinreal** [comment]
Yes, but not all people have insights on how it really worked, like me, I just look the stars of repo, if your repo actually faster than faster-whisper,

it would be good thing to higly suggested and highlights the weakness which other libs has when compare.

**Comment by thomasmol** [comment]
Feel free to write a blog post or article and publish it comparing different whisper implementations. As mentioned, there are now benchmarks in the readme: https://github.com/Vaibhavs10/insanely-fast-whisper#insanely-fast-whisper comparing faster-whisper with this repo.
