### ISSUE TITLE
Thank you very much for the improvements to whisper, could you have more clarity on whether there is an "hallucination" problem, i.e. an issue with duplicate output in other languages

### ISSUE THREAD

**Issue by isbn9877007** [Vaibhavs10/insanely-fast-whisper#61]
And can you give the amount of video memory required to run the model? Does the windows system require additional configuration?

**Comment by Vaibhavs10** [comment]
It still suffers from hallucination a bit. However, we have a fix for that coming up shortly.
See here: https://github.com/huggingface/transformers/pull/27492

It should work out of the box on Windows (as long as you have a GPU) - do check out the FAQs for more info: https://github.com/Vaibhavs10/insanely-fast-whisper#frequently-asked-questions

(I'm closing this issue for now, feel free to re-open)

**Comment by 152334H** [comment]
the code (on whisper v2/v3, with chunk_length_s=30) seems to still produce repeated text on long transcriptions, even on the latest transformers commit (i'll try to add examples later). behaviour doesn't occur on faster-whisper

adding repetition penalty kind of fixes this, but also still has unwanted consequences on the general quality of the transcript. beam search doesn't fix it
