### ISSUE TITLE
Difference between running insanely-fast-whisper with or without Flash Attention?

### ISSUE THREAD

**Issue by Arche151** [Vaibhavs10/insanely-fast-whisper#70]
Can someone maybe explain?

**Comment by Vaibhavs10** [comment]
Not sure if I understand your question, here's my attempt at answering it:
Flash Attention is a faster way of running the Attention operation through parallelism and better work partetioning. This results is fasteer inference time.

However, it only works on latest GPUs.

(Closing this for now, feel free to re-open)

**Comment by Arche151** [comment]
> Not sure if I understand your question, here's my attempt at answering it: Flash Attention is a faster way of running the Attention operation through parallelism and better work partetioning. This results is fasteer inference time.
> 
> However, it only works on latest GPUs.
> 
> (Closing this for now, feel free to re-open)

Ah, yeah, my question was kind of stupid, since it's visible from the Benchmarks that Flash Attention 2 enables faster interference. Thanks for answering anyway :)
