### ISSUE TITLE
Make it easy to import and use in other python modules

### ISSUE THREAD

**Issue by chamini2** [Vaibhavs10/insanely-fast-whisper#73]
I wanted to build on top of the work being done here (specially since diarization is coming soon) and I had to copy paste the transformers code into my code rather than 

```
from insanely_fast_whisper import pipe

pipe(...)
```

Or maybe 

```
from insanely_fast_whisper import build_pipe

pipe = build_pipe("large-v3", ...)
pip(...)
```

Can we get initial support for lib use?

**Comment by Vaibhavs10** [comment]
I'm not opposed to the idea. But I would let @patrick91 weigh in here!

**Comment by chamini2** [comment]
I think https://github.com/Vaibhavs10/insanely-fast-whisper/pull/42 is a good example where lib use would come in handy.

**Comment by patrick91** [comment]
@chamini2 I don't have time to implement it this week, but happy to review any PRs 😊
