### ISSUE TITLE
Repetition of same phrase several times in the output

### ISSUE THREAD

**Issue by bchinnari** [Vaibhavs10/insanely-fast-whisper#77]
I installed insanely-fast-whisper 2 weeks back.
I am using translate option of whisper-large-v2 model to convert ES wav to EN text. Some times, I get really long output text which is a repeat of small phrase as follows
```
 I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet. I'm going to tell you about the power of the internet.
```

I am using pipeline() functionality.
Is there any option/parameter to control this behaviour

**Comment by Vaibhavs10** [comment]
could you retry with `--task transcribe` & `--language en` please?

**Comment by Vaibhavs10** [comment]
Also, please update use `--model openai/whisper-large-v3`

**Comment by bchinnari** [comment]
Sure.. thank you for the quick response. I should use "transcribe" even if my input is Spanish wav to get en text??

**Comment by Vaibhavs10** [comment]
Yes! It should still work :)

**Comment by Vaibhavs10** [comment]
Closing this for now, feel free to re-open!

**Comment by bchinnari** [comment]
My input is spanish wav. I am observing considerable amount spanish text if I use "--task transcribe & --language en" .

**Comment by Vaibhavs10** [comment]
Interesting! That should not happen ideally (since that is the default behaviour of Whisper). Do you have any ideas about how good the audio quality is for the audio you are testing in?

Here's what I'd recommend:
1. Run with `--task translate --language en`
2. Reduce the number of `--batch-size 8` (or lower)
3. If the audio quality is not up to the mark then upsampling it or cleaning it might help loads.

**Comment by Vaibhavs10** [comment]
To clean the audio, you can use [demucs](https://github.com/facebookresearch/demucs)

Their API is quite simple:
Install demucs: `pip install -U demucs`
Clean the audio: `demucs --two-stems=vocals <FILE NAME>`

You can also use this Colab: https://github.com/Vaibhavs10/scratchpad/blob/main/demucs_basic_api.ipynb

**Comment by Vaibhavs10** [comment]
Hi @bchinnari - we resample it directly in `insanely-fast-whisper` so you don't need to worry about it.

**Comment by bchinnari** [comment]
One last question. I am trying to speed the whole process using num_workers option in pipeline().  But I get the warning that ASR not so accurate when we chunk and use num_workers (something like this). Kindly help me understand the cases when I can use that option.
