### ISSUE TITLE
Speaker diarization: TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by ackmanb** [Vaibhavs10/insanely-fast-whisper#79]
![diarization](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/79726390/dc710afe-2459-4cca-9fc7-5056b5351c54)
Error in diarization by chunks, by word works correctly. Looks like the audio is cut off in the middle of a word, Whisper did not predict an ending timestamp, and seems like it's happening because the end timestamp of the last segment is None

**Comment by Vaibhavs10** [comment]
Same as #76 Let's move the convo there, I'll fix it today! 🤗 

Closing this in favor of #76
