### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by deadcoder0904** [Vaibhavs10/insanely-fast-whisper#8]
noob here so don't know much about how to install this.

can you write a guide?

**Comment by deadcoder0904** [comment]
Does this work on a normal pc with no gpu, only cpu like `faster-whisper`?

Or only online using tpu? i saw another project which only used tpu. is this like this?

also, would love it if you guys can have standalone version like https://github.com/Purfview/whisper-standalone-win

**Comment by Vaibhavs10** [comment]
Hi @deadcoder0904 - This does require a GPU to work. I'll add instructions for CPU inference later this week.

**Comment by Herz3h** [comment]
Does it work with cpu if we follow instructions on the README? It says exclusive to NVIDIA Gpu

**Comment by patrick91** [comment]
@Herz3h not yet, I think we might CPU support this week: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/46
