### ISSUE TITLE
not compiled with CUDA error...solved?

### ISSUE THREAD

**Issue by BBC-Esq** [Vaibhavs10/insanely-fast-whisper#80]
I've encountered the same error that's outlined on in your readme, namely, the not compiled with cuda error.  Here's an example: Several users have reported it and all have been using Macs.  Here's one example: 

IMAGE OF CONVO~~

![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/108230321/4a5581c3-4d90-491f-98dd-10b12b70afcf)

According to this user, he solved the issue by commenting out a few lines of code... 

IMAGE OF CONVO~~

![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/108230321/a319c28a-b83d-4d13-9adf-f777187cd403)

This snippet he modified pertains to a user selecting "cuda" from a pulldown menu as a compute device...at which time my script populates another pulldown with the available quantizations from the ctranslate2 library per this [class here](https://opennmt.net/CTranslate2/python/ctranslate2.get_supported_compute_types.html?highlight=get_supported#ctranslate2.get_supported_compute_types)

I've since revised the code to remove this feature, but still have ctranslate2 check for supported quantizations at initialization (BOTH for cpu and cuda...not merely cuda if it's available), and it solved the issue for yet another user...and haven't had any complaints since.

Not sure if it helps, but it might have something to do with the program trying to either use a cuda device when it should use mps or cpu...or if not explicitly use the device (e.g. in inference) simply run a command that is specific to cuda...Not sure if Ctranslate2's class that prompted this error is using PyTorch under the hood, but if it is, that might pinpoint the issue...Hope this helps!

**Comment by Vaibhavs10** [comment]
You should be passing a `device mps` on a Mac. Mac doesn't support CUDA.

Ref: https://github.com/Vaibhavs10/insanely-fast-whisper#cli-options

**Comment by BBC-Esq** [comment]
I am aware that to use gpu-accleration on mac you set the device to "mps".    What I'm saying is...on the github readme for this repository it states:
{BEGIN QUOTE]
How to solve an AssertionError: Torch not compiled with CUDA enabled error on Windows?

The root cause of this problem is still unkown, however, you can resolve this by manually installing torch in the virtualenv like python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121. Thanks to @pto2k for all tdebugging this.
[END QUOTE]

My post was an attempt to help troubleshoot this a little since the readme states "The root cause of this problem is still unknown."...Therefore, I gave my experience, a user's solution on my github, to perhaps it help find an answer.

**Comment by Vaibhavs10** [comment]
Sorry I'm still a bit confused. The person in the screenshot appears to be using a CTranslate2 backend, whilst we use pure torch. 

I also have zero experience with Windows so no clue how all of this would work tbh!

**Comment by BBC-Esq** [comment]
It's the same error, perhaps the person who helped you troubleshoot it who you gave credit for, can take a look and you guys might find the ultimate answer.  It's probably just a piece of the puzzle though.  I wasn't able to definitively determine what the issue was, but we received the same errors so wanted to let you guys know.  Might help piece things together down the road.

BTW, just made a new issue that's kind of important to me at least.  Hope you get a chance to consider it.  Thanks!

**Comment by Vaibhavs10** [comment]
Responded! on the other thread!

(Closing this issue for now until this issue stops being resolved by the proposed fix)
(feel free to re-open if you feel otherwise 🤗 )
