### ISSUE TITLE
language error of output text

### ISSUE THREAD

**Issue by BearsEatLardCake** [Vaibhavs10/insanely-fast-whisper#84]
!insanely-fast-whisper --model-name distil-whisper/large-v2 --file-name /content/insanely-fast-whisper/audio/audio.wav --task transcribe --language zh
I run this code and its output is still English version, not Chinese

**Comment by Vaibhavs10** [comment]
Hi! @BearsEatLardCake - That is undesirable. Which version of `insanely-fast-whisper` are you on?

**Comment by Vaibhavs10** [comment]
Looked at it again, you're using `distil-whisper/large-v2`, which is an English-only model. Please switch to `openai/whisper-large-v3`

Closing this for now, feel free to reopen if the issue persists.
