### ISSUE TITLE
Is this only designed for CUDA-compatble GPUs? My device is not so; am I out of luck?

### ISSUE THREAD

**Issue by patria213** [Vaibhavs10/insanely-fast-whisper#9]

**Comment by Vaibhavs10** [comment]
Hi @patria213 - Which device are you on at the moment?

**Comment by patria213** [comment]
A windows pc: 
Edition	Windows 10 Home
Version	22H2

Processor	Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz   2.50 GHz
Installed RAM	6.00 GB
System type	64-bit operating system, x64-based processor

**Comment by patria213** [comment]
Hi, thanks for the reply. A windows pc:
Edition Windows 10 Home
Version 22H2

Processor Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz 2.50 GHz
Installed RAM 6.00 GB
System type 64-bit operating system, x64-based processor

**Comment by Vaibhavs10** [comment]
Hi @patria213 - You should be able to still leverage this via WSL.
