### ISSUE TITLE
ValueError: Soundfile is either not in the correct format or is malformed

### ISSUE THREAD

**Issue by simicvm** [Vaibhavs10/insanely-fast-whisper#90]
Trying to run:
`insanely-fast-whisper --file-name ../whisper.cpp/samples/jfk.wav --device-id mps --batch-size 4 --hf_token XYZ`

Getting the following error:
```
ValueError: Soundfile is either not in the correct format or is malformed. Ensure that the soundfile has a valid audio file extension (e.g. wav, flac or mp3) and is not corrupted. If reading from a remote URL, ensure that the URL is the full address to **download** the audio file.
```

I tried several different files and all of them give the same error. Meanwhile, I am able to transcribe them using `whisper.cpp`

<details><summary>Full error output</summary>
<p>

```
/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00dyld[39013]: Library not loaded: /opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib
  Referenced from: <8C2E2CF9-054E-300F-BDE7-3DE52F848638> /opt/homebrew/Cellar/librist/0.2.7_3/lib/librist.4.dylib
  Reason: tried: '/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/mbedtls/3.5.1/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mbedtls/3.5.1/lib/libmbedcrypto.14.dylib' (no such file), '/opt/homebrew/Cellar/mbedtls/3.5.1/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache)
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00
Traceback (most recent call last):
  File "/Users/marko/.local/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 254, in main
    outputs = pipe(
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1132, in __call__
    return next(
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 183, in __next__
    processed = next(self.subiterator)
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 434, in preprocess
    inputs = ffmpeg_read(inputs, self.feature_extractor.sampling_rate)
  File "/Users/marko/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/transformers/pipelines/audio_utils.py", line 41, in ffmpeg_read
    raise ValueError(
ValueError: Soundfile is either not in the correct format or is malformed. Ensure that the soundfile has a valid audio file extension (e.g. wav, flac or mp3) and is not corrupted. If reading from a remote URL, ensure that the URL is the full address to **download** the audio file.
``` 

</p>
</details> 

I used the following command to install the library which passed without any issues.
`pipx install insanely-fast-whisper --python python3.10` 

My system is:
- MacBook Pro M2 Pro
- macOS Sonoma 14.1.1
- Python 3.10

**Comment by byjlw** [comment]
Running into the same issue.

**Comment by byjlw** [comment]
Ran into the same issue. Following the steps outlined in the Overstack response fixed my issue.

**Comment by VpkPrasanna** [comment]
how to fix this in Ubuntu machine ?

> Hi @simicvm - I just looked through the stack trace, and this looks like an issue with the `ffmpeg` installation. I found this StackOverflow response, which offers some solutions: https://stackoverflow.com/questions/77110765/error-while-run-command-ffmpeg-library-not-loaded-opt-homebrew-opt-mbedtls-l
> 
> For context, we use ffmpeg to resample the audio into the format expected by Whisper. This helps us allow users to input any file, and we can resample and still process it.
> 
> (I'll keep this issue open till you confirm that fixes the problem. 🤗 )

**Comment by recog-arch** [comment]
Bump!

> how to fix this in Ubuntu machine ?
> 
> > Hi @simicvm - I just looked through the stack trace, and this looks like an issue with the `ffmpeg` installation. I found this StackOverflow response, which offers some solutions: https://stackoverflow.com/questions/77110765/error-while-run-command-ffmpeg-library-not-loaded-opt-homebrew-opt-mbedtls-l
> > For context, we use ffmpeg to resample the audio into the format expected by Whisper. This helps us allow users to input any file, and we can resample and still process it.
> > (I'll keep this issue open till you confirm that fixes the problem. 🤗 )

**Comment by recog-arch** [comment]
For anyone else facing this problem, the issue is in the way the audio file has been recorded. 

You have to first run something like:
`ffmpeg -i my_audio_file.mp3 -movflags faststart my_audio_file_fixed.mp3`
to move the metadata to the beggining of the file, soy the piping that the transformers library does over the audio file using ffmpeg would work.

**Comment by zivky** [comment]
@recog-arch solution solved this for me on Arch linux! Thank you!

**Comment by the-code-rider** [comment]
is it possible to re-open this issue. this error still pops up on windows

**Comment by adityamehra7** [comment]
> For anyone else facing this problem, the issue is in the way the audio file has been recorded.
> 
> You have to first run something like: `ffmpeg -i my_audio_file.mp3 -movflags faststart my_audio_file_fixed.mp3` to move the metadata to the beggining of the file, soy the piping that the transformers library does over the audio file using ffmpeg would work.

ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
