### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by hatched-MaciejPrzybylski** [Vaibhavs10/insanely-fast-whisper#94]
```
pipx install insanely-fast-whisper

pip seemed to fail to build package:
    optimum

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    FileNotFoundError: [Errno 2] No such file or directory: 'optimum/version.py'
    AssertionError: Error: Could not open 'optimum/version.py' due [Errno 2] No such file or directory: 'optimum/version.py'


```

any idea how to solve it? I'm using m1 mac

**Comment by Vaibhavs10** [comment]
Hi @hatched-MaciejPrzybylski - Sorry for the inconvenience. We currently only support Python 3.11 and below. 
@bt-nia also updated the readme to reflect the same: https://github.com/Vaibhavs10/insanely-fast-whisper#-blazingly-fast-transcriptions-via-your-terminal-%EF%B8%8F

I hope that helps. You should be able to run it in any other Python version. To do so, you can do something like:
`pipx install insanely-fast-whisper --python python3.10` or `pipx install insanely-fast-whisper --python python3.11`

(I'm closing this issue, but please do feel free to re-open it if the problem persists).

**Comment by hatched-MaciejPrzybylski** [comment]
that worked, thank you
